In [18]:
%load_ext autoreload
%autoreload 2
%matplotlib inline


import torchvision.transforms as transforms
import matplotlib.pyplot as plt 
import sys
import torch

sys.path.append("..")
import models 

student = models.MLP(layers=[1,5,2])
teacher = models.Mean_Teacher(student,alpha=0.5)

# make noise in student weights
with torch.no_grad():
    for p in student.parameters():
            print(p,p.shape)
            p.data = p.data + torch.rand(p.shape)*5
            break

for p in student.parameters():
    print(p,p.shape)
    break


for p in teacher.parameters():
    print(p,p.shape)
    break

teacher.update_weights(student)

for p in teacher.parameters():
    print(p,p.shape)
    break

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Parameter containing:
tensor([[-0.4590],
        [ 0.1209],
        [-0.1387],
        [-0.7804],
        [-0.3092]], requires_grad=True) torch.Size([5, 1])
Parameter containing:
tensor([[1.7972],
        [2.7664],
        [4.2086],
        [3.4214],
        [3.6969]], requires_grad=True) torch.Size([5, 1])
Parameter containing:
tensor([[-0.4590],
        [ 0.1209],
        [-0.1387],
        [-0.7804],
        [-0.3092]]) torch.Size([5, 1])
Parameter containing:
tensor([[0.6691],
        [1.4436],
        [2.0349],
        [1.3205],
        [1.6939]]) torch.Size([5, 1])
